/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "Platform_Types.h"


#define 	RCC_BASE			0X40021000
#define 	GPIOA_BASE			0X40010800

#define 	APB2ENR				*(vuint32*)(RCC_BASE+0X18)
#define		CRH					*(vuint32*)(GPIOA_BASE+0X04)
#define 	ODR					*(vuint32*)(GPIOA_BASE+0X0C)
//BIT FIELDS
#define RCC_IOPAEN 				(1<<2)
#define GPIOA13					(1UL<<13)

typedef union {
	vuint32 		all_fields;
		struct{
		vuint32 	reserved : 13;
		vuint32		p_13:1;
	}pin;
}R_ODR;

volatile R_ODR*  R_ODR_PTR = (volatile R_ODR*)(GPIOA_BASE+0X0C);


int main(void)
{
	APB2ENR |= RCC_IOPAEN;
	CRH &= 0XFF0FFFFF;
	CRH |= 0X00200000;

    /* Loop forever */
	while(1){
	R_ODR_PTR->pin.p_13 = 1;
	for(int i = 0; i<5000; i++);
	R_ODR_PTR->pin.p_13 = 0;
	for(int i = 0; i<5000; i++);
	}
}
