/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_IDR *(volatile uint32_t *)(GPIOA_BASE + 0x08)


//GPIOB
#define GPIOB_BASE 0x40010C00
#define GPIOB_CRH *(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_ODR *(volatile uint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_CRL *(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_IDR *(volatile uint32_t *)(GPIOB_BASE + 0x08)

//RCC registers
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CR *(volatile uint32_t *)(RCC_BASE + 0x00)
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE + 0x04)



void clock_init(void){
	//	Bit 2 IOPAEN: IO port A clock enable
	//	Set and cleared by software.
	//	0: IO port A clock disabled
	//	1: IO port A clock enabled

	RCC_APB2ENR |= (1<<2);


	//	Bit 3 IOPBEN: IO port B clock enable
	//	Set and cleared by software.
	//	0: IO port B clock disabled
	//	1: IO port B clock enabled
	RCC_APB2ENR |= (1<<3);

}

void GPIO_Init(void){
	GPIOA_CRL = 0x00;
	GPIOB_CRL =0x00;
	GPIOB_ODR =0x00;

	//PA1 input pin
	GPIOA_CRL &= ~(0b11<<4);  // input mode
	GPIOA_CRL |= (0b01<<6);  //01: Floating input (reset state)

	//PA13 input pin
	GPIOA_CRH &= ~(0b11<<20);  // input mode
	GPIOA_CRH |= (0b01<<22);  //01: Floating input (reset state)

	// PB1 is output push-pull pin
	GPIOB_CRL |= (0b01<<4);   //01: Output mode, max speed 10 MHz
	GPIOB_CRL &= ~(0b11<<6) ;   //00: General purpose output push-pull
	// PB13 is output push-pull pin
	GPIOB_CRH |= (0b01<<20);   //01: Output mode, max speed 10 MHz
	GPIOB_CRH &= ~(0b11<<22) ;   //00: General purpose output push-pull

}
int main(void)
{
	clock_init();
	GPIO_Init();

	while(1){

		if(!(GPIOA_IDR & (1<<1))){
			GPIOB_ODR ^= (1<<1);  //toggle PB1
			while(!(GPIOA_IDR & (1<<1)));
		}

		if((GPIOA_IDR & (1<<13))){
			GPIOB_ODR ^= (1<<13);  //toggle PB1

		}

		for(int i=0 ; i<255 ; i++);

	}

}
