/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)

#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CR *(volatile uint32_t *)(RCC_BASE + 0x00)
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE + 0x04)

int main(void)
{


	//Init GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	//	Bit 2 IOPAEN: IO port A clock enable
	//	Set and cleared by software.
	//	0: IO port A clock disabled
	//	1: IO port A clock enabled

	RCC_APB2ENR |= (1<<2);
	//
	//	Bit 0 HSION: Internal high-speed clock enable
	//Set and cleared by software.
	//Set by hardware to force the internal 8 MHz RC oscillator ON when leaving Stop or Standby
	//mode or in case of failure of the external 4-16 MHz oscillator used directly or indirectly as
	//system clock. This bit cannot be reset if the internal 8 MHz RC is used directly or indirectly
	//as system clock or is selected to become the system clock.
	//0: internal 8 MHz RC oscillator OFF
	//1: internal 8 MHz RC oscillator ON


//	RCC_CR |= (1<<24);		//PLLON now


	RCC_CFGR |= (0b10 << 0);		// set SW bits to choose HSI



	RCC_CFGR |= (0b0110<<18);		//PLLMUL *8

	RCC_CFGR |= (0b100 << 8);		// set APB1 to 16Mhz

	RCC_CFGR |= (0b101 << 11);		// set APB2 to 8Mhz
	RCC_CR |= (1<<24);		//PLLON now
	while(1)
	{
		GPIOA_ODR |= 1<<13 ;
		for (int i = 0; i < 5000; i++); // arbitrary delay
		GPIOA_ODR &= ~(1<<13) ;
		for (int i = 0; i < 5000; i++); // arbitrary delay
	}
}
